### ISSUE TITLE
Missed vanilla interaction `Water Source` + `Lava` = `Stone`

### ISSUE THREAD

**Issue by Krutoy242** [tttsaurus/Fluid-Interaction-Tweaker#3]
Only Cobblestone and Obsidian is listed in JEI, but there is should be third one with Stone.

![image](https://github.com/user-attachments/assets/c251596b-f50b-4e39-82e8-c95bdb863da8)

**Comment by tttsaurus** [comment]
well, i added the desc for `Stone`
![image](https://github.com/user-attachments/assets/c622b7ab-ef07-4bb6-bde5-014518f4d6ad)

showing various outputs requires me to refactor my framework and i dont decide to do that currently

the reason is that you can add whatever mechanism you want for the output block (so many variations are possible) by listening to the event, so i think showing desc for the output block is the best solution

**Comment by Krutoy242** [comment]
I believe players always bored to read. 
Can you make scrolling ingredient? I know JEI allow to make lists of items for a single slot. So it could just scroll between Cobble and Stone, so players will see different output without checking nasty texts.

**Comment by tttsaurus** [comment]
if im adding this scrolling feature, then it shouldn't be only vanilla compat. ill probably add some optional parameters in `addRecipe` method to display the scrolling things, but only for jei not really refactoring

do you think scrolling outputs + desc is enough?

**Comment by Krutoy242** [comment]
> some optional parameters

Why optional parameters? ZS have great tool [`IBlockPattern`](https://docs.blamejared.com/1.12/en/Vanilla/Blocks/IBlockPattern) that hold many blocks. Just make `outputBlock` parameter as pattern instead of `IBlock`.
The perfect solution would be if function could accept not only IBlockPattern but also `IIngredient` because im 100% sure that in my modpack i will make complicated interactions with resulted blocks that cant be interpreted as items to fit JEI item slot, such as vanilla fire. So, for actual interaction i will need to use block, but for JEI integration - item representation of this block.

> scrolling outputs + desc

No desc, only scrolling. Also, you dont need special handlers in your mod for description - ZS allows to add lore to item outputs.

**Comment by tttsaurus** [comment]
For the first thing,
![image](https://github.com/user-attachments/assets/acd5e3c9-d80e-4570-86fb-76e8f4d5c228)
this is why i was not considering `IIngredient`
in order to to be more generic, ill probably change that map value to `ComplexOutput` sth which is a class that is just in my mind, and it also requires refactorization

`ComplexOutput` should be able to spawn mobs items also by conditions sth. Then jei becomes huge, i really need some time to work on that

For the second thing,
if i finished the `ComplexOutput` and its corresponding jei compat, then desc or scrolling isn't a thing anymore

**Comment by tttsaurus** [comment]
![image](https://github.com/user-attachments/assets/6cf6cc57-f1e5-49a1-9a3d-fdb9f8945ad3)
![image](https://github.com/user-attachments/assets/7bfddc66-ce22-49d8-a00c-642c8ae69d14)
refer to v1.4.0-preview-1

**Comment by Krutoy242** [comment]
Looks great!

**Comment by Krutoy242** [comment]
In E2EE this tooltip looks shifted and out of tooltip panel. It position depends on GUI size. This may be related to [**ScalingGUIs**](https://www.curseforge.com/minecraft/mc-mods/scalingguis) mod.

![image](https://github.com/user-attachments/assets/916afb20-d796-43da-8700-64d1e6d43da5)

![image](https://github.com/user-attachments/assets/2fd934c2-7120-44f9-b51a-903b9bd5f2f9)

**Comment by tttsaurus** [comment]
i'll try to fix that. btw, why your thaumcraft is rendering aspects inside jei? i also have thaumcraft installed when testing

**Comment by Krutoy242** [comment]
Its some kind of addon i guess that adds aspects as tooltips.

**Comment by tttsaurus** [comment]
[fluidintetweaker-1.4.0-preview-1-hotfix-1.zip](https://github.com/user-attachments/files/17246551/fluidintetweaker-1.4.0-preview-1-hotfix-1.zip)

just for you to test (not a release)

**Comment by Krutoy242** [comment]
![image](https://github.com/user-attachments/assets/b3c4d5f0-9489-4f49-a34f-e4d4daf094f8)
Fixed!
