### ISSUE TITLE
[Feature Request] Add JEI fluid interaction recipe only

### ISSUE THREAD

**Issue by Krutoy242** [tttsaurus/Fluid-Interaction-Tweaker#4]
In large modpacks like [E2E-E](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended), there is tens of fluid interactions. It would be great if all of them will be listed in the same place.

Right now I made my own JEI tab page for this, but your implementation definitely better, since show more info such as "source" or "flowing".

![image](https://github.com/user-attachments/assets/36a472c5-4c26-4e4a-aa34-1b0bc45c7e94)

So, my request would be one of those
- Implement compatibility for all the mods with liquid interactions, such as ThermalDynamics or BionesOPlenty.
- Add zenscript function to add those recipes manually.

**Comment by tttsaurus** [comment]
for your requests

1. please give me some links since i dont know much about fluid interactions from other mods
2. ill add jei recipe only methods

im not sure how long it takes me to finish since currently busy with other things

**Comment by Krutoy242** [comment]
> please give me some links

Fetching list of those links may take quite some time! Can you assure me that my fetching work would not end up with feature abandoning? I know, people have real life and can't spend it on implementing features.

**Comment by tttsaurus** [comment]
adding some recipes manually is the easiest part here. no worries

**Comment by Krutoy242** [comment]
List of links describing custom interactions with environment:

- https://teamcofh.com/docs/1.12/thermal-foundation/primal-mana/
- https://teamcofh.com/docs/1.12/thermal-foundation/blazing-pyrotheum/
- https://teamcofh.com/docs/1.12/thermal-foundation/gelid-cryotheum/
- https://teamcofh.com/docs/1.12/thermal-foundation/tectonic-petrotheum/
- https://biomesoplenty.fandom.com/wiki/Blood
- https://biomesoplenty.fandom.com/wiki/Poisonous_Liquid (also same interactions with `Quicksand` and `Hot Spring Water`)
- https://biomesoplenty.fandom.com/wiki/Liquid_Honey (actually it turned into honey block with any liquid)
- https://ftb.fandom.com/wiki/Liquid_Starlight (its also generate `Aquamarine Shale`)
- https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/config/exnihilocreatio/WitchWaterWorldRegistry.json have complicated interactions based on weight and modpack configuration

![image](https://github.com/user-attachments/assets/f6e292a4-cbe2-42ad-9f46-63ff485398c6)

(took less time then i expected 😅)

**Comment by tttsaurus** [comment]
epic
thanks a lot

**Comment by tttsaurus** [comment]
there are many missing/hidden interactions from `biome o plenty`

e.g.
`blood` + `quick sand`
`water` + `quick sand`
`blood` + `poisonous liquid`
...

![image](https://github.com/user-attachments/assets/53df24c3-0f1a-4fc1-9c89-fd161c022e20)
interactions from `biome o plenty` are also problematic
in this case, `blood + water -> flesh` only works when `blood` is notifying `water` (probably using `NeighborNotifyEvent`). As a result, this recipe doesn't work when `water` is flowing to `blood`

my mod addresses this problem by introducing "backward notifying" so any recipe added using fluid interaction tweaker has a vanilla-like smooth behavior

due to these problems, im considering leave `biome o plenty` compat for now

btw `thermal foundation` compat is mostly done except some special interactions

**Comment by Krutoy242** [comment]
What kind of compat you leaving for BoP? Isnt you can just add JEI recipes about this interactions, even if they are not working stable?

**Comment by tttsaurus** [comment]
- just the jei recipes. i decide to stop here since there are too many hidden interactions. i prefer finish other features first
- yes im basically adding jei recipes but recipes don't look right due to bop's unstable interactions. however, the first claim is the main reason that i want to leave it for now

**Comment by tttsaurus** [comment]
[JEI-Only Recipes](https://github.com/tttsaurus/Fluid-Interaction-Tweaker/wiki/Methods#void-autoaddjeirecipeboolean-flag)
it's included in the latest release v1.4.0

add wiki is mostly done except events

**Comment by Krutoy242** [comment]
Great! I want to test this soon. This will make E2EE even more stable, because current [Plustweaks](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/ae3823e472fd70961b4d5062068a2e7857cf94fb/scripts/category/fluids.zs#L108-L109) mod implementation is kinda weird and causing block interact not always.

**Comment by tttsaurus** [comment]
what the title says for this issue is finished and im closing it

and other jei compats are still in the todo list

**Comment by Krutoy242** [comment]
Please upload mod so i could use this fix.

**Comment by tttsaurus** [comment]
which fix are you referring to? anyway, i decide to finish some other features first and probably bump to v1.5.0 release in the middle of Dec.
